name: Ovrlrd

options:
  bundleIdPrefix: com.ovrlrd
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.1"

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  Ovrlrd:
    type: application
    platform: iOS
    sources:
      - Ovrlrd
    dependencies:
      - package: MarkdownUI
    configFiles:
      Debug: Config/Local.xcconfig
      Release: Config/Local.xcconfig
    settings:
      base:
        INFOPLIST_FILE: Ovrlrd/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ovrlrd.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Ovrlrd/App/Ovrlrd.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        aps-environment: development
