#!/bin/bash
# Xcode Cloud CI script - runs after repository clone
# Generates Local.xcconfig from environment variables

set -e

echo "Generating Local.xcconfig from environment variables..."

CONFIG_DIR="$CI_PRIMARY_REPOSITORY_PATH/ios/Config"
CONFIG_FILE="$CONFIG_DIR/Local.xcconfig"

# Create config file from environment variables
cat > "$CONFIG_FILE" << EOF
// Auto-generated by ci_post_clone.sh for Xcode Cloud
// Do not edit - this file is created during CI builds

#include "Base.xcconfig"

DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM}
EOF

echo "Created $CONFIG_FILE"
echo "Contents:"
cat "$CONFIG_FILE"
